stages:
  - clone
  - test

test:
  stage: test
  script:
    - python get-pip.py
    - python -m pip install pygame
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - python thochienbinh.py run
